name: Release NPM Package

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      packages: write

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@baka-testing'
      - run: |
          npm dist-tag add @baka-testing/super-duper-ci-4@$(echo "${{github.ref_name}}" | cut -c 2-) latest
          exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
